project:
  type: book

book:
  title: "Introduction to Machine Learning for Physicists"
  author: "Maurizio Martinelli and Raffaele Gerosa"
  date: "3/2/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - dataset.qmd
    - basic_tools.qmd
    - basic_ml.qmd
    - first_ml_analysis.qmd
    - deep_learning_nn.qmd
    - wilks.qmd
    - deep_learning_cnn.qmd
    - deep_learning_rnn.qmd
    - deep_learning_gan.qmd
    - deep_learning_vae.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

